### ISSUE TITLE
Timeout - Option to override?

### ISSUE THREAD

**Issue by NoahKauffman** [matthewgilbert/pdblp#15]
Hi Mathew - 

Great package, I find your package super useful.  

I'm getting a timeout error from calls such as:

con.ref(['X US EQUITY', 'IBM US EQUITY'],['EQY_WEIGHTED_AVG_PX'],[('VWAP_START_DT','20170808'),('VWAP_END_DT','20170808'),('VWAP_START_TIME','11:00:00'),('VWAP_END_TIME','12:00:00')])

Error reads: "RuntimeError: Timeout, increase timeout parameter"

I see you ref timeout in method  _parse_ref() ...  Is there a simple way for user to override this; I couldn't find one in the docs?

Best,

Noah

**Comment by NoahKauffman** [comment]
I guess I should mention that I know how to do this by modifying the underlying code - but didn't know if there was a smarter way to do this without touching the code.

**Comment by matthewgilbert** [comment]
Glad you find it helpful.

This timeout option was originally added for `ref_hist` as a bit of a hack to essentially allow a bunch of iterative `ref` calls to be made which occasionally resulted in a `blpapi.Event.TIMEOUT`. I had never seen this occur before for a single `ref()` call and therefore it's currently not exposed.

One possible hacky solution (but preferable to a hardcoded fix) would be to use `ref_hist` instead use one of either `VWAP_START_DT` or `VWAP_END_DT` as the field to iterate over, something like
```python
tickers = ['X US EQUITY', 'IBM US EQUITY']
flds = ['EQY_WEIGHTED_AVG_PX']
dates = ['20170808']
ovrds = [('VWAP_END_DT', '20170808'), ('VWAP_START_TIME', '11:00:00'),
         ('VWAP_END_TIME', '12:00:00')]
con.ref_hist(tickers, flds, dates, date_field='VWAP_START_DT', ovrds=ovrds)
```

Unfortunately I don't currently have access to a Bloomberg connection so I can't confirm this works.

**Comment by NoahKauffman** [comment]
Cool, your solution does work! Thanks!

**Comment by matthewgilbert** [comment]
Okay great, somewhat of a round about way of doing things but glad it works. It would likely be better to add an instance variable with a default that the user can change and which is used throughout the `self.session.nextEvent()` calls but I am a bit hesitant to make changes without the ability to do any testing.

**Comment by NoahKauffman** [comment]
cool. Hit me up if you ever want to make any significant mods to the code (like for something more substantial than this). Happy to contribute and/or run tests for you. Thanks again for the reply.

**Comment by MarekOzana** [comment]
Hi Matthew,
I have the same issue with timeout in con.ref() call. Your workaround with ref_hist works nicely, but the proper fix (e.g. exposing timeout in con.ref()) would be nice.

**Comment by matthewgilbert** [comment]
Yes this is something I would like to implement. The fix is fairly straightforward so just a matter of testing against a Bloomberg connection. Will hopefully get something out in fairly short order.

**Comment by matthewgilbert** [comment]
This is now possible using the the `timeout` parameter when instantiating a `BCon` instance, e.g.

```python
import pdblp
con = pdblp.BCon(timeout=5000)
```

**Comment by gflores87** [comment]
Hi Matthew,

I'm updated pdblp and I get an error when I run the following command:

`con = pdblp.BCon(debug=False, port=8194,timeout=5000)`

TypeError: __init__() got an unexpected keyword argument 'timeout'

What could be happening?

**Comment by matthewgilbert** [comment]
Can you post the full stacktrace output to your screen.

**Comment by gflores87** [comment]
`Traceback (most recent call last):

  File "<ipython-input-6-3e678b5fe243>", line 1, in <module>
    runfile('C:/Users/gfloresgonzalez.PSP/Documents/Projects/Cap Arb/PSP_full_pdblp.py', wdir='C:/Users/gfloresgonzalez.PSP/Documents/Projects/Cap Arb')

  File "C:\Users\gfloresgonzalez.PSP\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\gfloresgonzalez.PSP\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/gfloresgonzalez.PSP/Documents/Projects/Cap Arb/PSP_full_pdblp.py", line 788, in <module>
    x,_ = CapArb_Intraday('US')

  File "C:/Users/gfloresgonzalez.PSP/Documents/Projects/Cap Arb/PSP_full_pdblp.py", line 758, in CapArb_Intraday
    bag_US = CapArb(market)

  File "C:/Users/gfloresgonzalez.PSP/Documents/Projects/Cap Arb/PSP_full_pdblp.py", line 746, in CapArb
    output['dfTR'],output['dfSpread_Value'] = get_Source_data(tickers,startDate,colNames,market)

  File "C:/Users/gfloresgonzalez.PSP/Documents/Projects/Cap Arb/PSP_full_pdblp.py", line 517, in get_Source_data
    con = pdblp.BCon(debug=False, port=8194,timeout = 5000)

TypeError: __init__() got an unexpected keyword argument 'timeout'`

**Comment by matthewgilbert** [comment]
I haven't actually pushed a release so you would need to install the dev
version from GitHub for the time being, if when you updated you meant from
PyPi. If you look at your source from pdblp.py does BCon() have the
parameter timeout?

On Feb 12, 2018 9:20 AM, "gflores87" <notifications@github.com> wrote:

`Traceback (most recent call last):

File "", line 1, in
runfile('C:/Users/gfloresgonzalez.PSP/Documents/Projects/Cap
Arb/PSP_full_pdblp.py',
wdir='C:/Users/gfloresgonzalez.PSP/Documents/Projects/Cap
Arb')

File "C:\Users\gfloresgonzalez.PSP\AppData\Local\Continuum\
anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705,
in runfile
execfile(filename, namespace)

File "C:\Users\gfloresgonzalez.PSP\AppData\Local\Continuum\
anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102,
in execfile
exec(compile(f.read(), filename, 'exec'), namespace)

File "C:/Users/gfloresgonzalez.PSP/Documents/Projects/Cap
Arb/PSP_full_pdblp.py", line 788, in
x,_ = CapArb_Intraday('US')

File "C:/Users/gfloresgonzalez.PSP/Documents/Projects/Cap
Arb/PSP_full_pdblp.py", line 758, in CapArb_Intraday
bag_US = CapArb(market)

File "C:/Users/gfloresgonzalez.PSP/Documents/Projects/Cap
Arb/PSP_full_pdblp.py", line 746, in CapArb
output['dfTR'],output['dfSpread_Value'] = get_Source_data(tickers,
startDate,colNames,market)

File "C:/Users/gfloresgonzalez.PSP/Documents/Projects/Cap
Arb/PSP_full_pdblp.py", line 517, in get_Source_data
con = pdblp.BCon(debug=False, port=8194,timeout = 5000)

TypeError: *init*() got an unexpected keyword argument 'timeout'`

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/matthewgilbert/pdblp/issues/15#issuecomment-364935749>,
or mute the thread

**Comment by matthewgilbert** [comment]
This release is now on pypi in `0.1.3`

**Comment by gflores87** [comment]
I see it now, thank you so much!
