### ISSUE TITLE
Add government lookup requests

### ISSUE THREAD

**Issue by dcragusa** [matthewgilbert/pdblp#45]
A function that returns a list of tickers corresponding to a generic govt. security such as 'T Govt'.

I don't feel comfortable opening a pull request due to so many style changes, but an implementation can be found in my fork [here](https://github.com/dcragusa/pdblp/blob/master/pdblp/pdblp.py#L641).

**Comment by matthewgilbert** [comment]
This looks interesting. I agree that a pull request in its current form wouldn't make sense since there is a lot going on here and I prefer sticking to atomic commits. Reproducing from your commits I see the following changes:

- Add type hints
- Refactor receiving events
- Simplify message parsing
- Robustify function arguments
- Add govt list function and test coverage
- Style changes
- Allow for changing host in unit testing

When I get some spare time I will look to incorporate some of these changes. I think most things look good although I will likely hold off on introducing types since this is a fairly major change and I would like to give it some thought prior to introducing the change.

**Comment by dcragusa** [comment]
That sounds good, I will make a separate branch with atomic commits sans type hints.

**Comment by matthewgilbert** [comment]
@dcragusa Some of these are now done. The features from your branch I have incorporated in recent commits 8340f324d91145255cc1c8df797cb66ad82bd073, d78791d2330949b74b41e9e196def75fc4758dba are:
- Refactor logger setup to improve clarity
- Refactor event handling into _receive_events()

**Comment by dcragusa** [comment]
Excellent, I will PR the govt list function soon.
